// platform-services/backstage/templates/_fragments/frontend/angular/skeleton/src/app/pages/about.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

// A second routed page — demonstrates multi-page client-side navigation. Because this is a
// real URL (/about), nginx must fall back to index.html on a hard refresh; nginx.conf does
// exactly that (try_files ... /index.html).
@Component({
  selector: 'app-about',
  standalone: true,
  imports: [RouterLink],
  template: `
    <section class="space-y-6">
      <h1 class="text-3xl font-bold tracking-tight">About</h1>
      <p class="text-slate-600">
        This starter ships the platform golden path: open a PR for a preview environment,
        merge to <code class="rounded bg-slate-200 px-1">main</code> for dev, tag
        <code class="rounded bg-slate-200 px-1">vX.Y.Z</code> for staging, and approve the
        manual gate for prod. You only edit the app source.
      </p>
      <ul class="list-disc space-y-1 pl-6 text-slate-600">
        <li>Framework: Angular + TypeScript</li>
        <li>Styling: Tailwind CSS</li>
        <li>Runtime: nginx (static files, non-root)</li>
        <li>Backend: relative <code class="rounded bg-slate-200 px-1">/api</code> calls</li>
      </ul>
      <a routerLink="/" class="inline-block text-indigo-600 underline">← Back home</a>
    </section>
  `,
})
export class AboutComponent {}

// platform-services/backstage/templates/_fragments/frontend/vue/skeleton/src/views/About.vue
<script setup lang="ts">
// A second routed view, to demonstrate client-side routing (vue-router). nginx falls back
// to index.html so /about resolves on a hard refresh too.
</script>

<template>
  <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm">
    <h2 class="mb-3 text-lg font-semibold">About ${{ values.appName }}</h2>
    <p class="text-sm text-slate-600">${{ values.description }}</p>
    <ul class="mt-4 list-disc space-y-1 pl-5 text-sm text-slate-600">
      <li>Vue 3 single-page app, built with Vite and TypeScript.</li>
      <li>Styled with Tailwind CSS v4.</li>
      <li>Calls the backend over a relative <code>/api</code> URL (same origin).</li>
      <li>Served in production by hardened nginx (non-root, read-only rootfs).</li>
    </ul>
  </section>
</template>
