// platform-services/backstage/templates/_fragments/frontend/nextjs/skeleton/src/app/page.tsx
'use client';

import { useEffect, useState } from 'react';

// The frontend talks to the backend over the SAME origin under /api. In production the
// platform ingress routes /api -> the backend component and / -> this Next.js server;
// in local dev, run the backend separately and reach it through a dev proxy, or just
// hit its own port directly while iterating. ALWAYS use a relative `/api/...` URL —
// never a hardcoded host (same convention as frontend/react's App.tsx).
type Health = {
  status: string;
};

export default function HomePage() {
  const [health, setHealth] = useState<Health | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch('/api/health')
      .then((res) => {
        if (!res.ok) throw new Error('GET /api/health -> HTTP ' + res.status);
        return res.json();
      })
      .then((data) => {
        if (!cancelled) setHealth(data);
      })
      .catch((e) => {
        if (!cancelled) setError(String(e));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <main className="mx-auto max-w-2xl p-8">
      <h1 className="text-3xl font-bold">${{ values.appName }}</h1>
      <p className="mt-2 text-gray-600">{${{ values.description | dump }}}</p>

      <p className="mt-6 text-gray-700">
        A Next.js (App Router, TypeScript) server frontend, styled with Tailwind,
        scaffolded onto the UA-MIS capstone golden path. It owns{' '}
        <code className="rounded bg-gray-100 px-1">/</code>; its paired backend owns{' '}
        <code className="rounded bg-gray-100 px-1">/api</code>.
      </p>

      <section className="mt-6 rounded-lg border border-gray-200 bg-gray-50 p-4">
        <h2 className="text-lg font-semibold">Backend health</h2>
        {health ? (
          <p className="mt-1 font-mono text-sm">status: {health.status}</p>
        ) : error ? (
          <p className="mt-1 text-sm text-red-700">{error}</p>
        ) : (
          <p className="mt-1 text-sm text-gray-500">Contacting the backend…</p>
        )}
      </section>

      <p className="mt-8 text-sm text-gray-500">
        <code className="rounded bg-gray-100 px-1">GET /healthz</code> — this
        component&apos;s own liveness/readiness probe (always 200).
      </p>
    </main>
  );
}

// platform-services/backstage/templates/_fragments/frontend/angular/skeleton/src/app/app.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { HttpClient } from '@angular/common/http';

// The frontend talks to the backend over the SAME origin under /api. In a frontend+backend
// project the platform ingress routes /api -> the backend and / -> this SPA; in local dev
// proxy /api to the backend. So ALWAYS use a relative `/api/...` URL — never a hardcoded
// host. Composed in the `single` slot (no backend), the health call simply fails gracefully.
interface Health {
  status: string;
  db: string;
  time: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <div class="min-h-screen bg-slate-50 text-slate-900">
      <header class="border-b border-slate-200 bg-white">
        <nav class="mx-auto flex max-w-3xl items-center justify-between px-4 py-4">
          <span class="text-lg font-bold tracking-tight">${{ values.appName }}</span>
          <div class="flex gap-6">
            <a
              routerLink="/"
              routerLinkActive="font-semibold text-indigo-600"
              [routerLinkActiveOptions]="{ exact: true }"
              class="text-slate-600 hover:text-slate-900"
              >Home</a
            >
            <a
              routerLink="/about"
              routerLinkActive="font-semibold text-indigo-600"
              class="text-slate-600 hover:text-slate-900"
              >About</a
            >
          </div>
        </nav>
      </header>

      <main class="mx-auto max-w-3xl px-4 py-10">
        <section class="mb-8 rounded-lg border border-slate-200 bg-white p-5 shadow-sm">
          <h2 class="mb-3 text-lg font-semibold">Backend health</h2>
          @if (health()) {
            <div class="flex items-center gap-3 text-sm">
              <span class="rounded bg-slate-100 px-2 py-1 font-mono">status: {{ health()!.status }}</span>
              <span class="rounded bg-slate-100 px-2 py-1 font-mono">db: {{ health()!.db }}</span>
              <span class="text-slate-500">{{ health()!.time }}</span>
            </div>
          } @else {
            <p class="text-sm text-slate-500">{{ error() ?? 'Contacting the backend…' }}</p>
          }
        </section>

        <router-outlet />
      </main>
    </div>
  `,
})
export class AppComponent implements OnInit {
  private readonly http = inject(HttpClient);
  readonly health = signal<Health | null>(null);
  readonly error = signal<string | null>(null);

  ngOnInit(): void {
    this.http.get<Health>('/api/health').subscribe({
      next: (h) => this.health.set(h),
      error: () =>
        this.error.set(
          'Backend /api not reachable — standalone mode (compose with a backend to enable).',
        ),
    });
  }
}
