// platform-services/backstage/templates/_fragments/frontend/solid/skeleton/src/index.tsx
import { render } from 'solid-js/web'
import { Router, Route } from '@solidjs/router'
import App from './App'
import Home from './pages/Home'
import About from './pages/About'
import './index.css'

const root = document.getElementById('root')

// App is the shared layout (root); pages render into props.children. nginx falls back to
// index.html so deep links resolve on a hard refresh.
render(
  () => (
    <Router root={App}>
      <Route path="/" component={Home} />
      <Route path="/about" component={About} />
    </Router>
  ),
  root!,
)

// platform-services/backstage/templates/_fragments/static/react-static/skeleton/src/main.tsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App.tsx'
import './index.css'

// SPA entrypoint. BrowserRouter gives clean client-side URLs (e.g. /about);
// nginx is configured (nginx.conf) to fall back to index.html for unknown paths
// so a hard refresh / deep link on a client route still serves the app.
const rootEl = document.getElementById('root')
if (!rootEl) {
  throw new Error('Root element #root not found in index.html')
}

createRoot(rootEl).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>,
)
